language: python3
python:
  - 3.6
install:
  - python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
  - python3 -m pip install -U pytest
script:
  - cd Discord
  - pytest
