sudo: false
language: python3
cache: pip
python:
  - 3.5.2
install:
  - python --version
  - python3 --version
  - pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
  - pip install -U pytest
script:
  - pytest Tests
