sudo: false
language: python3
cache: pip
python:
  - 3.6
install:
  - pip3 install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice] --cache-dir $HOME/.cache/pip
  - pip3 install -U pytest --cache-dir $HOME/.cache/pip
script:
  - pytest Tests
