sudo: false

language: python3

python: "3.6"

install:
  - python3 --version
  - pip3 install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
  - pip3 install -U pytest

script:
  - pytest Tests
