sudo: false

language: python

python: "3.6"

install:
  - python3 --version
  - pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
  - pip install -U pytest

script:
  - pytest Tests
