sudo: false

language: python

cache: pip

python:
  - "3.6"

install:
  - pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
  - pip install -U pytest
  - pip install -update google-api-python-client

script:
  - pytest Tests
