sudo: false

language: python3

cache: pip

python: "3.5"

install:
  - python3 --version
  - pip3 install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
  - pip3 install -U pytest

script:
  - pytest Tests
