sudo: false

language: python

cache: pip

matrix:
  include:
    - name: "Python 3.7"
      python: 3.7
      dist: xenial
      sudo: true
    - name: "Python 3.6"
      python: 3.6

services: mysql

script: PYTHONPATH=. python3 -m pytest tests
