sudo: false

language: python

cache: pip

python:
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

services: mysql

script: PYTHONPATH=./discord_talos python3 -m pytest tests
