
from typing import Optional, Any, Dict, Iterable
import utils.dutils as dutils
import discord.ext.commands as commands


class ExtendedBot(commands.Bot):

    all_events: Dict[str, dutils.EventLoop]

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def add_cog(self, cog: Any) -> None: ...

    def remove_cog(self, name: str) -> None: ...

    def load_extension(self, name: str, prefix: bool = ...) -> None: ...

    def unload_extension(self, name: str, prefix: bool = ...) -> None: ...

    def run(self, token: str, *args: Any, **kwargs: Any) -> None: ...

    def add_event(self, event: dutils.EventLoop) -> None: ...

    def remove_event(self, name: str) -> Optional[dutils.EventLoop]: ...

    def load_extensions(self, extensions: Iterable) -> int: ...

    def unload_extensions(self, extensions: Optional[Iterable] = ...) -> None: ...

    def find_command(self, command: str) -> Optional[commands.Command]: ...