
from typing import Tuple, Dict, List
from utils.element import Document, Node
import html.parser as parser

def attrs_to_dict(attrs: List[Tuple[str, str]]) -> Dict[str, List[str]]: ...

class TreeGen(parser.HTMLParser):

    heads: List[Node]
    cur: Node

    def __init__(self) -> None: ...

    def reset(self) -> None: ...

    def close(self) -> List[Node]: ...

    def error(self, message: str) -> None: ...

    def handle_starttag(self, tag: str, attrs: Tuple[Tuple[str, str]]) -> None: ...

    def handle_endtag(self, tag: str) -> None: ...

    def handle_data(self, data: str) -> None: ...
