
from typing import Tuple, Dict, List, Iterable, Union, Optional
from utils.element import Node, Element
import html.parser as parser

def attrs_to_dict(attrs: Iterable[Tuple[str, str]]) -> Dict[str, Union[str, List[str]]]: ...

class TreeGen(parser.HTMLParser):

    heads: List[Element]
    cur: Optional[Node]

    def __init__(self) -> None: ...

    def reset(self) -> None: ...

    def close(self) -> List[Element]: ...

    def error(self, message: str) -> None: ...

    def handle_starttag(self, tag: str, attrs: Tuple[Tuple[str, str]]) -> None: ...

    def handle_endtag(self, tag: str) -> None: ...

    def handle_data(self, data: str) -> None: ...
