"""
    Talos utils stub file
"""

from typing import Dict, List
import logging
import pathlib
import discord.ext.commands as dcommands
import utils.element as el


fullwidth_transform: Dict[str, str] = ...
tz_map: Dict[str, float] = ...
log_folder: pathlib.Path

def configure_logger(logger: logging.Logger, *, handlers: List[logging.Handler] = ..., formatter: logging.Formatter = ..., level: int = ..., propagate: bool = ...): ...

def words_written(time: int, wpm: int) -> int: ...

def time_to_write(words: int, wpm: int) -> int: ...

def key_generator(size: int = ..., chars: str = ...) -> str: ...

def log_error(logger: logging.Logger, level: int, error: Exception, message: str = ...) -> None: ...

def safe_remove(*filenames: str) -> None: ...

def replace_escapes(text: str) -> str: ...

def to_snake_case(text: str, upper: bool = ...) -> str: ...

def to_camel_case(text: str, upper: bool = ...) -> str: ...

def add_spaces(text: str) -> str: ...

def zero_pad(text: str, length: int) -> str: ...

def to_dom(html: str) -> el.Document: ...

def to_nodes(html: str) -> List[el.Node]: ...
