
from typing import Dict, Any, Optional
import aiohttp.web as web
import aiohttp
import pathlib
import website.api_handler as api

from utils.twitch.twitch_app import TwitchApp

Path = pathlib.Path
SETTINGS_FILE: str = ...
BACKUP_ERROR: str = ...
KNOWN_MIMES: Dict[str, str]

class TalosPrimaryHandler:

    _settings: Dict[str, Any]
    webmaster: Dict[str, str]
    base_path: Path
    session: aiohttp.ClientSession
    twitch_app: Optional[TwitchApp]
    api_handler: api.APIHandler

    def __new__(cls, app: web.Application = ..., settings: Dict[str, Any] = ...) -> TalosPrimaryHandler: ...

    def __init__(self, app: web.Application = ..., settings: Dict[str, Any] = ...) -> None: ...

    def __sinit__(self, app: web.Application = ..., settings: Dict[str, Any] = ...) -> None: ...

    async def site_get(self, request: web.Request) -> web.Response: ...

    async def api_get(self, request: web.Request) -> web.Response: ...

    async def do_head(self, request: web.Request) -> web.Response: ...

    async def api_post(self, request: web.Request) -> web.Response: ...

    async def get_path(self, path: str) -> Path: ...

    async def get_response(self, path: Path, status: int = ..., *, request: web.Request = ...) -> web.Response: ...

    async def python_page(self, path: Path, status: int = ..., *, request: web.Request = ...) -> web.Response: ...

    async def error_code(self, code: int, error: Exception = ...) -> web.Response: ...

    async def backup_error_code(self, old_code: int, new_code: int, error: Exception = ...) -> web.Response: ...

    async def guess_mime(self, path: Path) -> str: ...


def main() -> int: ...
