
from typing import Dict, Any
import aiohttp.web as web
import pathlib

Path = pathlib.Path
SETTINGS_FILE: str = ...
BACKUP_ERROR: str = ...
KNOWN_MIMES: Dict[str, str] = ...
counter: int = ...

class ServerError(Exception): ...

class ServerWarning(Warning): ...

class TalosApplication(web.Application):

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def apply_settings(self, settings: Dict[str, Any]) -> None: ...

    async def get_path(self, path: str) -> pathlib.Path: ...

    async def get_response(self, path: pathlib.Path, status: int = ..., *, request: web.Request = ...) -> web.Response: ...

    async def python_page(self, path: pathlib.Path, status: int = ..., *, request: web.Request = ...) -> web.Response: ...

    async def error_code(self, status: int, error: Exception = ...) -> web.Response: ...

    async def backup_error_code(self, old_code: int, new_code: int, error: Exception = ...) -> web.Response: ...

    async def guess_mime(self, path: pathlib.Path) -> str: ...

def load_settings() -> Dict[str, Any]: ...

def main() -> int: ...
