"""
    CommandLang stub file.

    author: CraftSpider
"""
from typing import Dict, List, Any, TypeVar
import discord.ext.commands as commands
import abc

T = TypeVar("T")

def get_sub(obj: Any, attribute: str) -> Any: ...

_op_priority: Dict[str, int] = ...
_op_functions: Dict[str, callable] = ...

class CommandLangError(Exception): ...

class CommandLangInterpreter(metaclass=abc.ABCMeta):

    DEFAULT_PRIORITY: Dict[str, int] = ...
    DEFAULT_FUNCS: Dict[str, callable] = ...

    @staticmethod
    def operators_exist(command_str: str) -> bool: ...

    @staticmethod
    def get_exec_list(expression: str) -> List[str]: ...

    def exec_op(self, ops: List[str], values: List[str]) -> None: ...

    def get_priority(self, operator: str) -> int: ...

    def get_function(self, operator: str) -> callable: ...

    def evaluate(self, context: T, exec_list: List[str]) -> bool: ...

    def parse_lang(self, context: T, command_str: str) -> str: ...

    @abc.abstractmethod
    def process_val(self, context: T, val: str) -> Any: ...

    @abc.abstractmethod
    def execute_command(self, context: T, val: str) -> bool: ...

class DiscordCL(CommandLangInterpreter):

    def execute_command(self, ctx: commands.Context, item: str) -> bool: ...

    def process_val(self, ctx: commands.Context, val: str) -> Any: ...