
from typing import Dict, Any, Callable
import aiohttp.web as web
import utils.webserver.handlers.base_handler as bh

def api_handler(name: str) -> Callable[[Callable], Callable]: ...

class APIHandler(bh.BaseHandler):

    __slots__ = ()

    def __init_subclass__(cls, **kwargs: Any) -> None: ...

    def _check_token(self, user: str, token: str) -> bool: ...

    def _path_to_name(self, path: str) -> str: ...

    async def get(self, request: web.Request) -> web.Response: ...

    async def post(self, request: web.Request) -> web.Response: ...

    async def dispatch_request(self, method: str, request: web.Request) -> web.Response: ...

    async def dispatch(self, path: str, method: str, data: Dict[str, Any]) -> web.Response: ...
