
from typing import Dict
import http.server as hserver
import pathlib

Path = pathlib.Path
HTML_PATH: pathlib.Path = ...
WEBMASTER_EMAIL: str = ...
BACKUP_ERROR: str = ...
KNOWN_MIMES: Dict[str, str]

class TalosServerHandler(hserver.BaseHTTPRequestHandler):

    def do_GET(self) -> None: ...

    def do_POST(self) -> None: ...

    def serve_file(self, path: Path, head: bool = ...) -> Path: ...

    def get_path(self, path: str) -> Path: ...

    def error_code(self, code: int) -> None: ...

    def backup_error_code(self, old_code: int, new_code: int, error: Exception) -> None: ...

    def guess_mime(self, path: Path) -> str: ...

    def send_file(self, path: Path, *, code: int = ..., mime_type: str = ..., head: bool = ...) -> None: ...