
from typing import Dict
import aiohttp.web as web
import pathlib

Path = pathlib.Path
HTML_PATH: pathlib.Path = ...
WEBMASTER_EMAIL: str = ...
BACKUP_ERROR: str = ...
KNOWN_MIMES: Dict[str, str]

class TalosPrimaryHandler:

    async def do_get(self, request: web.Request) -> web.Response: ...

    async def do_head(self, request: web.Request) -> web.Response: ...

    async def do_post(self, request: web.Request) -> web.Response: ...

    async def get_path(self, path: str) -> Path: ...

    async def get_response(self, path: Path) -> web.Response: ...

    async def error_code(self, code: int) -> web.Response: ...

    async def backup_error_code(self, old_code: int, new_code: int, error: Exception) -> web.Response: ...

    async def guess_mime(self, path: Path) -> str: ...
